(() => {
  'use strict';
  const canvas = document.getElementById('game'), ctx = canvas.getContext('2d');
  const TAU = Math.PI * 2, DPR_CAP = 2;
  const input = { steer: 0, throttle: false, brake: false, handbrake: false, pointers: new Map(), joyId: null };
  const state = { mode: 'menu', score: 0, best: Number(localStorage.getItem('etd_best') || 0), combo: 1, maxCombo: 1, driftBest: 0, driftNow: 0, runTime: 0, distance: 0, shake: 0 };
  const car = { x: 0, speed: 0, slide: 0, lean: 0, road: true };
  const view = { w: 0, h: 0, dpr: 1, roadX: 0 };
  const road = { width: 0, segments: [] }, particles = [];
  const audio = { ctx: null, engine: null, gain: null };

  function resize() {
    view.dpr = Math.min(devicePixelRatio || 1, DPR_CAP); view.w = innerWidth; view.h = innerHeight;
    canvas.width = Math.floor(view.w * view.dpr); canvas.height = Math.floor(view.h * view.dpr);
    canvas.style.width = `${view.w}px`; canvas.style.height = `${view.h}px`; ctx.setTransform(view.dpr, 0, 0, view.dpr, 0, 0);
    road.width = Math.min(view.w * .48, Math.max(230, view.h * .72)); view.roadX = view.w / 2;
  }
  function makeRoad() {
    road.segments.length = 0; let x = 0, curve = 0;
    for (let i = 0; i < 430; i++) { if (i % 25 === 0) curve = (Math.random() - .5) * 1.8; x = clamp(x + curve * 6, -road.width * .52, road.width * .52); road.segments.push({ x, curve, object: i % 17 === 0 ? (i % 34 ? 'tree' : 'lamp') : null }); }
  }
  function reset() {
    state.mode = 'play'; state.score = 0; state.combo = 1; state.maxCombo = 1; state.driftBest = 0; state.driftNow = 0; state.runTime = 0; state.distance = 0; state.shake = 0;
    car.x = 0; car.speed = 0; car.slide = 0; car.lean = 0; car.road = true; particles.length = 0; document.body.classList.add('playing'); startAudio();
  }
  function update(dt) {
    if (state.mode === 'play') updateCar(dt); updateParticles(dt); state.shake = Math.max(0, state.shake - dt * 16); updateAudio();
  }
  function updateCar(dt) {
    const throttle = input.throttle ? 1 : 0, brake = input.brake ? 1 : 0, hand = input.handbrake ? 1 : 0;
    car.speed += ((throttle ? 330 : 220) - car.speed) * dt * (brake ? 4.5 : 1.7); if (brake) car.speed -= 170 * dt; if (!throttle && !brake) car.speed -= 24 * dt; car.speed = clamp(car.speed, 0, 390);
    const steer = input.steer, grip = hand ? 1.8 : 5.7, slidePower = hand ? 210 : (throttle ? 48 : 0);
    car.slide += (steer * slidePower - car.slide * grip) * dt; car.x += (steer * (72 + car.speed * .22) + car.slide) * dt; car.x = clamp(car.x, -road.width * .64, road.width * .64); car.lean += ((steer * .28 + car.slide * .0016) - car.lean) * dt * 8;
    state.distance += car.speed * dt; state.runTime += dt; const edge = road.width * .46; car.road = Math.abs(car.x) < edge; if (!car.road) { car.speed = Math.max(70, car.speed - 110 * dt); spawnDust(dt); }
    const drifting = car.road && car.speed > 145 && (Math.abs(car.slide) > 18 || hand);
    if (drifting) { state.driftNow += dt; state.driftBest = Math.max(state.driftBest, state.driftNow); state.combo = Math.min(9.9, state.combo + dt * .3); state.maxCombo = Math.max(state.maxCombo, state.combo); state.score += dt * (car.speed * .12 + Math.abs(car.slide) * 1.5) * state.combo; if (Math.random() < dt * (4 + Math.abs(car.slide) / 35)) spawnSmoke(); }
    else { state.driftNow = Math.max(0, state.driftNow - dt * 2.5); if (state.driftNow === 0) state.combo = Math.max(1, state.combo - dt * .5); }
    if (Math.abs(car.x) > road.width * .58) { car.x *= .96; state.shake = Math.max(state.shake, 3); } if (state.distance > 10500) finish();
  }
  function finish() { state.mode = 'result'; state.best = Math.max(state.best, Math.round(state.score)); localStorage.setItem('etd_best', state.best); document.body.classList.remove('playing'); }
  function spawnSmoke() { const side = Math.random() < .5 ? -1 : 1; particles.push({ type: 'smoke', x: car.x + side * 25, y: .75, vx: side * (4 + Math.random() * 9), life: .55 + Math.random() * .4, max: 1, r: 5 + Math.random() * 7 }); if (particles.length > 100) particles.shift(); }
  function spawnDust(dt) { if (Math.random() > dt * 16) return; particles.push({ type: 'dust', x: car.x + (Math.random() - .5) * 30, y: .78, vx: 0, life: .35, max: .35, r: 3 + Math.random() * 4 }); }
  function updateParticles(dt) { for (let i = particles.length - 1; i >= 0; i--) { const p = particles[i]; p.life -= dt; p.y += dt * .04; p.x += p.vx * dt; if (p.life <= 0) particles.splice(i, 1); } }
  function project(i) { const index = Math.min(road.segments.length - 1, Math.floor((state.distance + i * 34) / 34)); const seg = road.segments[index]; const z = i / 68; return { x: view.roadX + seg.x * (.52 + z * .48), y: view.h * .5 - z * view.h * .66, scale: .52 + z * .48, seg }; }
  function draw() { ctx.save(); ctx.translate((Math.random() - .5) * state.shake, (Math.random() - .5) * state.shake); drawBackground(); if (state.mode === 'menu') drawMenu(); else { drawRoad(); drawParticles(); drawCar(); drawHud(); if (state.mode === 'result') drawResult(); } ctx.restore(); }
  function drawBackground() { ctx.fillStyle = '#13251b'; ctx.fillRect(0, 0, view.w, view.h); const l = view.w * .18, r = view.w * .82; ctx.fillStyle = '#0d1c15'; ctx.fillRect(l, 0, r - l, view.h); for (let i = 0; i < 18; i++) { const x = (i * 97 + 33) % Math.max(1, view.w * .17), y = (i * 131 + state.distance * .16) % view.h; ctx.fillStyle = i % 2 ? '#1e3a29' : '#244631'; ctx.beginPath(); ctx.arc(x + 18, y, 14 + i % 3 * 5, 0, TAU); ctx.fill(); ctx.beginPath(); ctx.arc(view.w - x - 18, (y + 70) % view.h, 15 + i % 4 * 4, 0, TAU); ctx.fill(); } }
  function drawRoad() {
    const left = [], right = []; for (let i = 0; i <= 20; i++) { const p = project(i * 3.8), half = road.width * (.22 + p.scale * .78) * .5; left.push({ x: p.x - half, y: p.y }); right.push({ x: p.x + half, y: p.y }); }
    ctx.beginPath(); ctx.moveTo(left[0].x, left[0].y); left.slice(1).forEach(p => ctx.lineTo(p.x, p.y)); right.slice().reverse().forEach(p => ctx.lineTo(p.x, p.y)); ctx.closePath(); ctx.fillStyle = '#4b4d4b'; ctx.fill();
    ctx.strokeStyle = '#dad8c8'; ctx.lineWidth = 5; ctx.beginPath(); left.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.stroke(); ctx.beginPath(); right.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.stroke();
    for (let i = 1; i < 17; i += 2) { const p = project(i * 3.4), q = project(i * 3.4 + 1.3); ctx.strokeStyle = 'rgba(242,239,213,.8)'; ctx.lineWidth = 5 + p.scale * 9; ctx.beginPath(); ctx.moveTo(p.x, p.y); ctx.lineTo(q.x, q.y); ctx.stroke(); }
    for (let i = 2; i < 20; i += 4) drawRoadside(project(i * 3.6)); ctx.fillStyle = 'rgba(0,0,0,.22)'; ctx.fillRect(0, view.h * .2, view.w * .18, view.h * .8); ctx.fillRect(view.w * .82, view.h * .2, view.w * .18, view.h * .8);
  }
  function drawRoadside(p) { const s = p.scale, side = p.seg.object === 'lamp' ? -1 : (p.seg.x % 2 ? 1 : -1), x = p.x + side * road.width * (.55 + s * .35), y = p.y; if (p.seg.object === 'lamp') { ctx.strokeStyle = '#737e71'; ctx.lineWidth = 3 * s; ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x, y - 64 * s); ctx.stroke(); ctx.fillStyle = '#f6d98a'; ctx.beginPath(); ctx.arc(x, y - 66 * s, 5 * s, 0, TAU); ctx.fill(); } else { ctx.fillStyle = '#1e432b'; ctx.beginPath(); ctx.arc(x, y - 18 * s, 25 * s, 0, TAU); ctx.fill(); ctx.fillStyle = '#6b5137'; ctx.fillRect(x - 3 * s, y - 12 * s, 6 * s, 24 * s); } }
  function drawParticles() { particles.forEach(p => { const a = clamp(p.life / p.max, 0, 1), x = view.roadX + p.x + p.vx * 2, y = view.h * .78 - (1 - p.y) * 90; ctx.globalAlpha = a * .65; ctx.fillStyle = p.type === 'smoke' ? '#e5e8e3' : '#9b8466'; ctx.beginPath(); ctx.arc(x, y, p.r * (1 + (1 - a)), 0, TAU); ctx.fill(); }); ctx.globalAlpha = 1; }
  function drawCar() { const x = view.roadX + car.x, y = view.h * .74, w = Math.min(74, view.h * .15), h = w * 1.55; ctx.save(); ctx.translate(x, y); ctx.rotate(car.lean * .2); ctx.fillStyle = 'rgba(0,0,0,.35)'; ctx.beginPath(); ctx.ellipse(0, h * .18, w * .52, h * .68, 0, 0, TAU); ctx.fill(); ctx.fillStyle = '#15181b'; ctx.beginPath(); ctx.roundRect(-w * .43, -h * .5, w * .86, h, w * .22); ctx.fill(); ctx.fillStyle = '#c84a36'; ctx.beginPath(); ctx.roundRect(-w * .35, -h * .44, w * .7, h * .88, w * .19); ctx.fill(); ctx.fillStyle = '#252e33'; ctx.beginPath(); ctx.roundRect(-w * .27, -h * .18, w * .54, h * .32, w * .1); ctx.fill(); ctx.fillStyle = '#8aafb2'; ctx.fillRect(-w * .22, -h * .13, w * .44, h * .12); ctx.fillStyle = '#e7d3ac'; ctx.fillRect(-w * .25, h * .16, w * .5, h * .08); ctx.fillStyle = '#f2e5b8'; ctx.fillRect(-w * .28, -h * .38, w * .56, h * .05); ctx.restore(); }
  function drawHud() { ctx.fillStyle = '#f4f2e9'; ctx.font = '800 14px Arial'; ctx.fillText(`${Math.round(car.speed * .46)} KM/H`, 24, 30); ctx.fillText(`${Math.round(state.score)} PTS`, 24, 51); ctx.textAlign = 'right'; ctx.fillText(`x${state.combo.toFixed(1)}`, view.w - 24, 30); ctx.fillText(`${state.runTime.toFixed(1)} s`, view.w - 24, 51); ctx.textAlign = 'left'; if (state.driftNow > .18) { ctx.fillStyle = '#f7d47c'; ctx.font = '900 22px Arial'; ctx.textAlign = 'center'; ctx.fillText('DRIFT', view.w / 2, view.h * .32); ctx.font = '800 14px Arial'; ctx.fillText(`+${Math.round(state.driftNow * state.combo * 60)}`, view.w / 2, view.h * .32 + 22); ctx.textAlign = 'left'; } drawControls(); }
  function buttonCircle(x, y, r, label, active, color) { ctx.fillStyle = active ? (color || '#c59a54') : 'rgba(18,25,21,.72)'; ctx.strokeStyle = active ? '#fff1c6' : '#bcb8a3'; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(x, y, r, 0, TAU); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#f4f2e9'; ctx.font = `900 ${Math.max(11, r * .25)}px Arial`; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText(label, x, y); ctx.textAlign = 'left'; ctx.textBaseline = 'alphabetic'; }
  function drawControls() { const base = Math.min(view.w, view.h), r = Math.max(42, base * .105), jx = view.w * .085, jy = view.h - r * 1.2; buttonCircle(jx, jy, r * 1.2, 'СТИК', input.joyId !== null); ctx.strokeStyle = '#e0d8c3'; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(jx + input.steer * r * .75, jy, r * .42, 0, TAU); ctx.stroke(); const gx = view.w * .91, gy = view.h - r * 1.1; buttonCircle(gx, gy, r * 1.15, 'ГАЗ', input.throttle, '#c64f39'); buttonCircle(gx - r * 1.3, gy - r * .9, r * .7, 'Т', input.brake); buttonCircle(gx - r * 1.35, gy + r * .55, r * .7, 'Р', input.handbrake); }
  function drawMenu() { ctx.textAlign = 'center'; ctx.fillStyle = '#f4f2e9'; ctx.font = `900 ${Math.min(38, view.w * .045)}px Arial`; ctx.fillText('ENDLESS TOUGE', view.w / 2, view.h * .3); ctx.fillText('DRIFT', view.w / 2, view.h * .3 + 43); ctx.fillStyle = '#d1b66c'; ctx.font = '800 14px Arial'; ctx.fillText('VERTICAL ACTION RUN', view.w / 2, view.h * .3 + 75); ctx.fillStyle = '#c84a36'; ctx.beginPath(); ctx.roundRect(view.w / 2 - 90, view.h * .56, 180, 58, 12); ctx.fill(); ctx.fillStyle = '#fff4dc'; ctx.font = '900 20px Arial'; ctx.fillText('START', view.w / 2, view.h * .56 + 36); ctx.font = '700 13px Arial'; ctx.fillStyle = '#d7d2bf'; ctx.fillText(`BEST ${Math.round(state.best)} PTS`, view.w / 2, view.h * .7); ctx.textAlign = 'left'; }
  function drawResult() { ctx.fillStyle = 'rgba(7,12,9,.86)'; ctx.fillRect(view.w * .27, view.h * .2, view.w * .46, view.h * .6); ctx.textAlign = 'center'; ctx.fillStyle = '#f4f2e9'; ctx.font = '900 26px Arial'; ctx.fillText('RUN COMPLETE', view.w / 2, view.h * .31); ctx.font = '700 15px Arial'; ctx.fillText(`SCORE  ${Math.round(state.score)}`, view.w / 2, view.h * .4); ctx.fillText(`MAX COMBO  x${state.maxCombo.toFixed(1)}`, view.w / 2, view.h * .45); ctx.fillText(`BEST DRIFT  ${state.driftBest.toFixed(1)} s`, view.w / 2, view.h * .5); ctx.fillStyle = '#c84a36'; ctx.fillRect(view.w / 2 - 80, view.h * .61, 160, 48); ctx.fillStyle = '#fff4dc'; ctx.font = '900 16px Arial'; ctx.fillText('ЕЩЁ РАЗ', view.w / 2, view.h * .61 + 30); ctx.textAlign = 'left'; }
  function pointerDown(e) { e.preventDefault(); const p = { x: e.clientX, y: e.clientY }; input.pointers.set(e.pointerId, p); const base = Math.min(view.w, view.h), r = Math.max(42, base * .105), jx = view.w * .085, jy = view.h - r * 1.2, gx = view.w * .91, gy = view.h - r * 1.1; if (state.mode === 'menu' && Math.abs(p.x - view.w / 2) < 150 && p.y > view.h * .5 && p.y < view.h * .7) { reset(); return; } if (state.mode === 'result') { reset(); return; } if (Math.hypot(p.x - jx, p.y - jy) < r * 1.6) { input.joyId = e.pointerId; setSteer(p.x, jx, r); } if (Math.hypot(p.x - gx, p.y - gy) < r * 1.5) input.throttle = true; if (Math.hypot(p.x - (gx - r * 1.3), p.y - (gy - r * .9)) < r * .85) input.brake = true; if (Math.hypot(p.x - (gx - r * 1.35), p.y - (gy + r * .55)) < r * .85) input.handbrake = true; }
  function pointerMove(e) { if (e.pointerId === input.joyId) { const r = Math.max(42, Math.min(view.w, view.h) * .105); setSteer(e.clientX, view.w * .085, r); } }
  function setSteer(x, center, r) { input.steer = clamp((x - center) / (r * .9), -1, 1); }
  function pointerUp(e) { input.pointers.delete(e.pointerId); if (e.pointerId === input.joyId) { input.joyId = null; input.steer = 0; } if (input.pointers.size === 0) { input.throttle = false; input.brake = false; input.handbrake = false; } }
  ['pointerdown', 'pointermove', 'pointerup', 'pointercancel'].forEach(type => canvas.addEventListener(type, type === 'pointerdown' ? pointerDown : type === 'pointermove' ? pointerMove : pointerUp, { passive: false }));
  addEventListener('resize', resize); addEventListener('keydown', e => { if (e.key === 'ArrowLeft' || e.key === 'a') input.steer = -1; if (e.key === 'ArrowRight' || e.key === 'd') input.steer = 1; if (e.key === ' ') input.handbrake = true; if (e.key === 'ArrowUp' || e.key === 'w') input.throttle = true; if (e.key === 'ArrowDown' || e.key === 's') input.brake = true; });
  addEventListener('keyup', e => { if (/ArrowLeft|ArrowRight|a|d/.test(e.key)) input.steer = 0; if (e.key === ' ') input.handbrake = false; if (/ArrowUp|w/.test(e.key)) input.throttle = false; if (/ArrowDown|s/.test(e.key)) input.brake = false; });
  function startAudio() { if (!audio.ctx) { audio.ctx = new (window.AudioContext || window.webkitAudioContext)(); audio.engine = audio.ctx.createOscillator(); audio.gain = audio.ctx.createGain(); audio.engine.type = 'sawtooth'; audio.engine.connect(audio.gain).connect(audio.ctx.destination); audio.gain.gain.value = .018; audio.engine.start(); } audio.ctx.resume(); }
  function updateAudio() { if (audio.engine) audio.engine.frequency.value = 70 + car.speed * .75; }
  function clamp(v, a, b) { return Math.max(a, Math.min(b, v)); }
  function loop(t) { const dt = Math.min(.033, (t - (loop.last || t)) / 1000); loop.last = t; update(dt); draw(); requestAnimationFrame(loop); }
  resize(); makeRoad(); requestAnimationFrame(loop);
})();
